paths: 
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags: 
        - Products
      responses:
        "200":
          description: Los productos se obtuvieron correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del server
    post:
      summary: Crea un producto
      tags: 
        - Products
      responses:
        "201":
          description: El producto se creo correctamente
        "500":
          description: Error interno del server
  /api/products/{uid}:
    get:
      summary: Obtiene un solo producto
      tags: 
        - Products
      responses:
        "200":
          description: El producto se obtuvo correctamente
        "500":
          description: Error interno del server
      parameters:
        - name: uid
          in: path
          required: true
          description: id del producto que se solicita observar
          schema:
            $type: String
    put:
      summary: Modifica un solo producto
      tags: 
        - Products
      responses:
        "200":
          description: El producto se modifico correctamente
        "500":
          description: Error interno del server
      parameters:
        - name: uid
          in: path
          required: true
          description: id del producto que se solicita actualizar
          schema:
            $type: String
      requestBody: 
        required: true
        content:
          application/json:
            schema: 
              $ref: '#components/requestBodies/updateProduct'
    delete:
      summary: Elimina un solo producto
      tags: 
        - Products
      responses:
        "200":
          description: El producto se elimino correctamente
        "500":
          description: Error interno del server
      parameters:
        - name: uid
          in: path
          required: true
          description: id del producto que se solicita eliminar
          schema:
            $type: String

components:
  schemas:
    Product:
      type: object
      properties: 
        id:
          type: String
          description: Id autogenerado de mongo
        title: 
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Informacion del producto
        stock:
          type: Number
          description: Cantidad de stock que hay del producto
        price:
          type: Number
          description: Precio del producto
        thumbnail:
          type: String
          description: Link de la foto del producto
        owner:
          type: String
          description: Usuario que publico dicho producto
      example:
        _id: ObjectId("asdfasdfgfagas5465as45s")
        title: Audi A4
        description: Sedan aleman muy confiable
        stock: 10
        price: 50000
        thumbnail: www.asdadasdasda4546ad.com
        owner: admin

  requestBodies:
    updateProduct:
      type: object
      properties:
        id:
          type: String
          description: Id autogenerado de mongo
        title: 
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Informacion del producto
        stock:
          type: Number
          description: Cantidad de stock que hay del producto
        price:
          type: Number
          description: Precio del producto
        thumbnail:
          type: String
          description: Link de la foto del producto
        owner:
          type: String
          description: Usuario que publico dicho producto
        